// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsWXOi4APMNSCSTuKeZ3pdIbyXbxgUEs4',
    appId: '1:369670218792:web:4be6db5fa66f561186811d',
    messagingSenderId: '369670218792',
    projectId: 'kindrop-d6823',
    authDomain: 'kindrop-d6823.firebaseapp.com',
    storageBucket: 'kindrop-d6823.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrYova47Kvryeyc2vSZidP2vDhJraCtDk',
    appId: '1:369670218792:android:8dca305049af192d86811d',
    messagingSenderId: '369670218792',
    projectId: 'kindrop-d6823',
    storageBucket: 'kindrop-d6823.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_nfSropGzx3A9pd6F0s3JS39aGTD66UA',
    appId: '1:369670218792:ios:00131245312085fd86811d',
    messagingSenderId: '369670218792',
    projectId: 'kindrop-d6823',
    storageBucket: 'kindrop-d6823.firebasestorage.app',
    iosClientId: '369670218792-gu1t37180qt2nvb5lceol6tb395tn9hf.apps.googleusercontent.com',
    iosBundleId: 'com.example.kindrop1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_nfSropGzx3A9pd6F0s3JS39aGTD66UA',
    appId: '1:369670218792:ios:00131245312085fd86811d',
    messagingSenderId: '369670218792',
    projectId: 'kindrop-d6823',
    storageBucket: 'kindrop-d6823.firebasestorage.app',
    iosClientId: '369670218792-gu1t37180qt2nvb5lceol6tb395tn9hf.apps.googleusercontent.com',
    iosBundleId: 'com.example.kindrop1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsWXOi4APMNSCSTuKeZ3pdIbyXbxgUEs4',
    appId: '1:369670218792:web:b1acb8654fc1475886811d',
    messagingSenderId: '369670218792',
    projectId: 'kindrop-d6823',
    authDomain: 'kindrop-d6823.firebaseapp.com',
    storageBucket: 'kindrop-d6823.firebasestorage.app',
  );
}
